apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
  zone: europe-west1-b


####HOW TO REQUEST IT
apiVersion: v1
        kind: PersistentVolumeClaim
        metadata:
          name: mongodb-pvc
         spec:
  storageClassName: fast
  resources:
    requests:
      storage: 100Mi
  accessModes:
      - ReadWriteOnce 
