apiVersion: v1
kind: Service
metadata:
   name: hello-service
   labels:
     app: hello
     namespace: assignment
spec:
   type: NodePort
   ports:
     - port: 8080
       nodePort: 30101
   selector:
     app: hello
     version: 2.0.0
