apiVersion: v1
kind: ReplicationController
...
spec:
  ...
  template:
... spec:
      containers:
      - name: kubia
        image: luksa/kubia
        readinessProbe:
          exec:
            command:
            - ls
            - /var/ready
