apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-canary
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: hello
        rollout: canary 
        namespace: assignment
    spec:
      containers:
        - name: hello
          image: "d0x2f/http-hello-world:v2.0.0"
          ports:
            - name: http
              containerPort: 8080
            - name: health
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 1
